### PR TITLE
Fix sysmacros.h include for GNU/Hurd

### PR DESCRIPTION
**Pull request by sthibaul**

### CODE REVIEW

**Comment by andreasabel** [comment]
@sthibaul Thanks for the PR, Samuel.

Could you provide some evidence along with that change?  CI is neutral about it.
How about some documentation of the `__GNU__` flag or some article explaining it (and thus arguing for the correctness)?

**Comment by sthibaul** [comment]
> Could you provide some evidence along with that change

The upstream header is at

https://sourceware.org/git/?p=glibc.git;a=blob;f=sysdeps/mach/hurd/bits/sysmacros.h;h=04ab5ad09abbd4274582a6af20e27b544b8a30c9;hb=HEAD

> `__GNU__`

This is specified in the porting guidelines, in the  GNU specific #define section:
https://www.gnu.org/software/hurd/hurd/porting/guidelines.html
(yes, `__GNU__` is defined on GNU/Hurd only, as it was from the start to be "the" GNU system)

**Comment by andreasabel** [comment]
Thanks!

Release candidate: https://hackage.haskell.org/package/unix-compat-0.7.3/candidate

**Review by andreasabel — APPROVED** [review]

**Comment by andreasabel** [comment]
Published as 0.7.3.

**Pull request merged**
